//
//  SearchViewController.swift
//  Movve
//
//  Created by Victor Rubenko on 04.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import SnapKit

final class SearchViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: SearchPresenterInterface!
    
    // MARK: - Private properties -
    
    private lazy var tableView: UITableView = {
        let tableView = UITableView()
        tableView.backgroundColor = .clear
        tableView.delegate = self
        tableView.dataSource = self
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 44
        tableView.keyboardDismissMode = .onDrag
        tableView.register(SearchTableViewCell.self, forCellReuseIdentifier: SearchTableViewCell.identifier)
        return tableView
    }()
    
    private lazy var searchController: UISearchController = {
        let sc = UISearchController()
        sc.searchBar.delegate = self
        sc.searchBar.scopeButtonTitles = presenter.scopes
        sc.searchBar.showsCancelButton = false
        sc.hidesNavigationBarDuringPresentation = false
        sc.searchBar.keyboardAppearance = .dark
        return sc
    }()
    
    private var setFirstResponser = true
    private var keyboardShowNotification: Any!
    private var keyboardHideNotification: Any!
    private var tableBottomConstraint: Constraint!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupNavigationItem()
        setupGestureRecognizers()
        setupViews()
        setupConstraints()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        tabBarController?.tabBar.isHidden = true
        setupNavigationAppearance()
        setupObservers()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        tabBarController?.tabBar.isHidden = false
        removeObservers()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if setFirstResponser {
            setFirstResponser = false
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                self.searchController.searchBar.searchTextField.becomeFirstResponder()
            }
        }
    }
}

private extension SearchViewController {
    func setupViews() {
        view.backgroundColor = .appBackground
        
        view.addSubview(tableView)
    }
    
    func setupConstraints() {
        tableView.snp.makeConstraints { make in
            make.top.equalTo(view.safeAreaLayoutGuide)
            make.leading.equalToSuperview()
            make.trailing.equalToSuperview()
            tableBottomConstraint = make.bottom.equalToSuperview().constraint
        }
    }
    
    func setupNavigationItem() {
        title = "Search"
        navigationItem.searchController = searchController
        navigationItem.hidesSearchBarWhenScrolling = false
    }
    
    func setupNavigationAppearance() {
        let appearance = UINavigationBarAppearance()
        appearance.configureWithTransparentBackground()
        navigationController?.navigationBar.standardAppearance = appearance
        navigationController?.navigationBar.scrollEdgeAppearance = appearance
    }
    
    func setupObservers() {
        keyboardHideNotification = NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillHide),
            name: UIResponder.keyboardWillHideNotification,
            object: nil)
        
        keyboardShowNotification = NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillShow),
            name: UIResponder.keyboardWillShowNotification,
            object: nil)
    }
    
    func removeObservers() {
        NotificationCenter.default.removeObserver(keyboardShowNotification!)
        NotificationCenter.default.removeObserver(keyboardHideNotification!)
    }
    
    func setupGestureRecognizers() {
        let tapRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTap))
        tapRecognizer.cancelsTouchesInView = false
        view.addGestureRecognizer(tapRecognizer)
    }
}

// MARK: - Private Actions -

private extension SearchViewController {
    @objc func keyboardWillShow(_ notification: NSNotification) {
        guard let keyboardSize = (notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?
                .cgRectValue else { return }
        tableBottomConstraint.deactivate()
        tableView.snp.makeConstraints { make in
            tableBottomConstraint = make.bottom.equalToSuperview().offset(-keyboardSize.height).constraint
        }
    }
    
    @objc func keyboardWillHide(_ notification: NSNotification) {
        tableBottomConstraint.deactivate()
        tableView.snp.makeConstraints { make in
            tableBottomConstraint = make.bottom.equalToSuperview().constraint
        }
    }
    
    @objc func handleTap(_ recognizer: UITapGestureRecognizer) {
        searchController.searchBar.endEditing(true)
    }
}

// MARK: - Extensions -

extension SearchViewController: SearchViewInterface {
    func reloadData() {
        tableView.reloadData()
    }
}

extension SearchViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        presenter.numberOfItems
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(
            withIdentifier: SearchTableViewCell.identifier,
            for: indexPath) as! SearchTableViewCell
        cell.configure(presenter.item(for: indexPath))
        cell.selectionStyle = .none
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        presenter.didSelectItem(at: indexPath)
    }
}

extension SearchViewController: UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        presenter.searchData(query: searchBar.text)
    }
    
    func searchBar(_ searchBar: UISearchBar, selectedScopeButtonIndexDidChange selectedScope: Int) {
        presenter.didSelectScope(index: selectedScope, query: searchBar.text)
    }
}
