//
//  SearchInterfaces.swift
//  Movve
//
//  Created by Victor Rubenko on 04.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SearchWireframeInterface: WireframeInterface {
    func navigateToMovieDetails(movieId: Int)
    func navigateToTVShowDetails(tvShowId: Int)
}

protocol SearchViewInterface: ViewInterface {
    func reloadData()
}

protocol SearchPresenterInterface: PresenterInterface {
    var scopes: [String] { get }
    var numberOfItems: Int { get }
    
    func searchData(query: String?)
    func item(for indexPath: IndexPath) -> ItemModel
    func didSelectItem(at indexPath: IndexPath)
    func didSelectScope(index: Int, query: String?)
}

protocol SearchInteractorInterface: InteractorInterface {
    func searchMovies(query: String, completion: @escaping (Result<[ItemModel], Error>) -> Void)
    func searchTVShows(query: String, completion: @escaping (Result<[ItemModel], Error>) -> Void)
}
