//
//  TVShowDetailsWireframe.swift
//  Movve
//
//  Created by Victor Rubenko on 02.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TVShowDetailsWireframe: BaseWireframe<TVShowDetailsViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(tvShowId: Int) {
        let moduleViewController = TVShowDetailsViewController()
        super.init(viewController: moduleViewController)

        let interactor = TVShowDetailsInteractor()
        let presenter = TVShowDetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, mapper: Mapper.shared, tvShowId: tvShowId)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TVShowDetailsWireframe: TVShowDetailsWireframeInterface {
    func openURL(url: URL) {
        let alert = UIAlertController(title: nil, message: "Do you want to open link in external browser?", preferredStyle: .alert)
        let okAction = UIAlertAction(title: "Yes", style: .default) { _ in
            UIApplication.shared.open(url, options: [:], completionHandler: nil)
        }
        let cancelAction = UIAlertAction(title: "No", style: .default, handler: nil)
        alert.addAction(okAction)
        alert.addAction(cancelAction)
        navigationController?.present(alert, animated: true, completion: nil)
    }
}
