//
//  TVShowDetailsInteractor.swift
//  Movve
//
//  Created by Victor Rubenko on 02.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TVShowDetailsInteractor {
    private let movieDBService: MovieDBServiceProcotol
    private let dataService: DataServiceProtocol
    
    init(
        movieDBService: MovieDBServiceProcotol = MovieDBService.shared,
        dataService: DataServiceProtocol = RealmDataService.shared
    ) {
        self.movieDBService = movieDBService
        self.dataService = dataService
    }
}

// MARK: - Extensions -

extension TVShowDetailsInteractor: TVShowDetailsInteractorInterface {

    func getTVShowDetails(id tvShowId: Int, completion: @escaping (Result<TVShowDetails, Error>) -> Void)  {
        movieDBService.getTVShowDetails(id: tvShowId, completion: completion)
    }
    
    func getCast(id tvShowId: Int, completion: @escaping (Result<Credits, Error>) -> Void) {
        movieDBService.getTVShowCredits(id: tvShowId, completion: completion)
    }
    
    func getTVShowVideos(id tvShowId: Int, completion: @escaping (Result<[Video], Error>) -> Void) {
        movieDBService.getTVShowVideos(id: tvShowId, completion: completion)
    }
    
    func addToFavorites(tvShow: TVShowDetails) {
        dataService.addToFavorite(tvShow: tvShow)
    }
    
    func removeFromFavorites(tvShowId: Int) {
        dataService.removeFromFavorites(tvShowId: tvShowId)
    }
    
    func isInFavorite(tvShowId: Int) -> Bool {
        dataService.isTVShowInFavorites(tvShowId: tvShowId)
    }
    
}
