//
//  TabBarInterfaces.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol TabBarWireframeInterface: WireframeInterface {
}

protocol TabBarViewInterface: ViewInterface {
}

protocol TabBarPresenterInterface: PresenterInterface {
}
