//
//  TabBarWireframe.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Swinject

final class TabBarWireframe: BaseWireframe<TabBarViewController> {

    // MARK: - Private properties -
    
    // MARK: - Module setup -

    init() {
        let moduleViewController = TabBarViewController()
        super.init(viewController: moduleViewController)

        let presenter = TabBarPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
        
    }

}

// MARK: - Extensions -

extension TabBarWireframe: TabBarWireframeInterface {
}
