//
//  MovieDetailsInteractor.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieDetailsInteractor {
    private let movieDBService: MovieDBServiceInterface
    private let dataService: DataServiceInterface
    
    init(
        movieDBService: MovieDBServiceInterface = MovieDBService.shared,
        dateService: DataServiceInterface = RealmDataService.shared
    ) {
        self.movieDBService = movieDBService
        self.dataService = dateService
    }
}

// MARK: - Extensions -

extension MovieDetailsInteractor: MovieDetailsInteractorInterface {
    
    func getMovieDetails(id movieId: Int, completion: @escaping (Result<MovieDetails, Error>) -> Void)  {
        movieDBService.getMovieDetails(id: movieId, completion: completion)
    }
    
    func getCast(id movieId: Int, completion: @escaping (Result<Credits, Error>) -> Void) {
        movieDBService.getMovieCredits(id: movieId, completion: completion)
    }
    
    func getMovieVideos(id movieId: Int, completion: @escaping (Result<[Video], Error>) -> Void) {
        movieDBService.getMovieVideos(id: movieId, completion: completion)
    }
    
    func addToFavorites(movie: MovieDetails) {
        dataService.addToFavorite(item: movie)
    }
    
    func removeFromFavorites(movieId: Int) {
        dataService.removeFromFavorites(id: movieId, kind: .Movie)
    }
    
    func isInFavorite(movieId: Int) -> Bool {
        dataService.isInFavorites(id: movieId, kind: .Movie)
    }
    
}
