//
//  MovieDetailsInterfaces.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MovieDetailsSectionType {
    case posterInfo, overview, cast, rating, watchNow, video
}

protocol MovieDetailsWireframeInterface: WireframeInterface {
    func openURL(url: URL)
}

protocol MovieDetailsViewInterface: ViewInterface {
    func reloadData()
    func reloadFavorite()
}

protocol MovieDetailsPresenterInterface: PresenterInterface {
    var movie: MovieDetailsModel? { get }
    var cast: [CastMemberModel] { get }
    var sections: [MovieDetailsSectionType] { get }
    var videos: [Video] { get }
    var isInFavorite: Bool { get }
    
    func loadData()
    func selectWatchNow()
    func tapFavorite()
}

protocol MovieDetailsInteractorInterface: InteractorInterface {
    func getMovieDetails(id movieId: Int, completion: @escaping (Result<MovieDetails, Error>) -> Void)
    func getCast(id movieId: Int, completion: @escaping (Result<Credits, Error>) -> Void)
    func getMovieVideos(id movieId: Int, completion: @escaping (Result<[Video], Error>) -> Void)
    
    func addToFavorites(movie: MovieDetails)
    func removeFromFavorites(movieId: Int)
    func isInFavorite(movieId: Int) -> Bool
}
