//
//  FavoritesInterfaces.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FavoritesWireframeInterface: WireframeInterface {
}

protocol FavoritesViewInterface: ViewInterface {
}

protocol FavoritesPresenterInterface: PresenterInterface {
}

protocol FavoritesInteractorInterface: InteractorInterface {
}
