//
//  FavoritesInterfaces.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FavoritesWireframeInterface: WireframeInterface {
    func navigateToMovieDetails(movieId: Int)
    func navigateToTVShowDetails(tvShowId: Int)
}

protocol FavoritesViewInterface: ViewInterface {
    func reloadData()
    func removeItem(at indexPath: IndexPath)
}

protocol FavoritesPresenterInterface: PresenterInterface {
    var items: [FavoriteModel] { get }
    var segments: [String] { get }
    
    func loadData()
    func didSelectSegment(index: Int)
    func item(for indexPath: IndexPath) -> FavoriteModel
    func didSelectItem(indexPath: IndexPath)
    func swapToRemove(indexPath: IndexPath)
}

protocol FavoritesInteractorInterface: InteractorInterface {
    func getFavoriteMovies() -> [FavoriteModel]
    func getFavoriteTVShows() -> [FavoriteModel]
    func removeFavoriteMovie(id: Int)
    func removeFavoriteTVShow(id: Int)
}
