//
//  FavoritesWireframe.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FavoritesWireframe: BaseWireframe<FavoritesViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = FavoritesViewController()
        super.init(viewController: moduleViewController)

        let interactor = FavoritesInteractor()
        let presenter = FavoritesPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension FavoritesWireframe: FavoritesWireframeInterface {
}

extension FavoritesWireframe: TabBarViewType {
    var tabIcon: UIImage {
        UIImage(systemName: "bookmark") ?? UIImage()
    }
    
    var tabTitle: String? {
        nil
    }
    
    var tabView: UIViewController {
        viewController
    }
}
