//
//  MovieDetailsWireframe.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailsWireframe: BaseWireframe<MovieDetailsViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = MovieDetailsViewController()
        super.init(viewController: moduleViewController)

        let interactor = MovieDetailsInteractor()
        let presenter = MovieDetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MovieDetailsWireframe: MovieDetailsWireframeInterface {
}
