//
//  TVDetailsPresenter.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TVDetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: TVDetailsViewInterface
    private let interactor: TVDetailsInteractorInterface
    private let wireframe: TVDetailsWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: TVDetailsViewInterface,
        interactor: TVDetailsInteractorInterface,
        wireframe: TVDetailsWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension TVDetailsPresenter: TVDetailsPresenterInterface {
}
