//
//  HomeWireframe.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeWireframe: BaseWireframe<HomeViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = HomeViewController()
        super.init(viewController: moduleViewController)

        let interactor = HomeInteractor()
        let presenter = HomePresenter(view: moduleViewController, interactor: interactor, wireframe: self, mapper: Mapper.shared)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension HomeWireframe: HomeWireframeInterface {
    func navigateToMovieDetails(id: Int) {
        
        navigationController?.topViewController?.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        navigationController?.pushWireframe(MovieDetailsWireframe(movieId: id))
    }
    
    func navigateToTVDetails(id: Int) {
        navigationController?.topViewController?.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        navigationController?.pushWireframe(TVShowDetailsWireframe(tvShowId: id))
    }
    
}

extension HomeWireframe: TabBarViewType {
    var tabIcon: UIImage {
        UIImage(systemName: "house") ?? UIImage()
    }
    
    var tabTitle: String? {
        "Home"
    }
    
    var tabView: UIViewController {
        viewController
    }
}

