//
//  HomeInterfaces.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {

}

protocol HomeViewInterface: ViewInterface {

}

protocol HomePresenterInterface: PresenterInterface {

}

protocol HomeInteractorInterface: InteractorInterface {

}
