//
//  HomeInteractor.swift
//  Movve
//
//  Created by Victor Rubenko on 30.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
    private let movieDBService: MovieDBService
    
    init(movieDBService: MovieDBService = .shared) {
        self.movieDBService = movieDBService
    }
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
    func getMovies(completion: @escaping (Result<[Movie], Error>) -> Void) {
        movieDBService.discoverMovies(completion: completion)
    }
    
    func getTVShows(completion: @escaping (Result<[TVShow], Error>) -> Void) {
        movieDBService.discoverTVShows(completion: completion)
    }
}
