//
//  TVShowDetailsInterfaces.swift
//  Movve
//
//  Created by Victor Rubenko on 02.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum TVShowDetailsSectionType {
    case overview, cast, rating, watchNow, video
}

protocol TVShowDetailsWireframeInterface: WireframeInterface {
    func openURL(url: URL)
}

protocol TVShowDetailsViewInterface: ViewInterface {
    func reloadData()
}

protocol TVShowDetailsPresenterInterface: PresenterInterface {
    var tvShow: TVShowDetailsModel? { get }
    var cast: [CastMemberModel] { get }
    var sections: [TVShowDetailsSectionType] { get }
    var videos: [Video] { get }
    
    func loadData()
    func selectWatchNow()
}

protocol TVShowDetailsInteractorInterface: InteractorInterface {
    func getTVShowDetails(id movieId: Int, completion: @escaping (Result<TVShowDetails, Error>) -> Void)
    func getCast(id movieId: Int, completion: @escaping (Result<Credits, Error>) -> Void)
    func getTVShowVideos(id movieId: Int, completion: @escaping (Result<[Video], Error>) -> Void)
}
